- name: Deploy swingby node (btc_eth)
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: remove swingby node
      shell: |
        docker rm -f swingby_node 2> /dev/null || true
      register: output

    - debug: var=output.stdout_lines

    - name: restart swingby node
      shell: |
        docker image prune -af
        docker pull swingbylabs/swapd-go:0.1.3-sp
        docker run -d --restart unless-stopped \
          --cpus 2.0 \
          --name swingby_node \
          --net=bridge \
          -v /var/swingby/node/{{NETWORK}}:/var/node_data \
          -p 12121:12121 \
          -p 8067:8067 \
          --log-opt max-size=10m --log-opt max-file=5 \
          swingbylabs/swapd-go:0.1.3-sp \
          --home "/var/node_data" \
          --logger.level {{LOG_LEVEL}} \
          -k {{K_UNTIL}} \
          --p2p.connect {{BOOTSTRAP_NODE_1}} \
          --p2p.connect {{BOOTSTRAP_NODE_2}} \
          --p2p.connect {{BOOTSTRAP_NODE_3}}

      register: output

    - debug: var=output.stdout_lines

    - name: download node-agent & start agent
      shell: |
        rm -rf node-agent-master
        wget -q https://github.com/SwingbyProtocol/node-agent/archive/master.tar.gz
        tar -xf master.tar.gz         
        rm master.tar.gz
        cd node-agent-master
        killall node-agent
        nohup bin/linux_amd64/node-agent -c swingby_node -o /var/swingby/agent.json > node-agent.log &
        
      register: output

    - debug: var=output.stdout_lines
