- name: Restart infura
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: download latest docker-blockbook repo && restart infura nodes
      shell: |
        if [ -d "/var/swingby/node/mainnet_btc_eth" ]; then 
          rm -rf /var/swingby/node/btc_eth
          mkdir -p /var/swingby/node/btc_eth
          cp -r /var/swingby/node/mainnet_btc_eth/* /var/swingby/node/btc_eth/
        fi
        rm -rf docker-blockbook-master
        wget -q https://github.com/SwingbyProtocol/docker-blockbook/archive/master.tar.gz
        tar -xf master.tar.gz         
        rm -f master.tar.gz

        docker system prune -f
        cd docker-blockbook-master/deployments/mainnet
        docker pull ethereum/client-go:v1.10.1
        DIR=/var/swingby docker-compose down
        DIR=/var/swingby docker-compose up -d --build bitcoind geth
        sleep 40
        DIR=/var/swingby docker-compose up -d --build bb_btc bb_eth

      register: output

    - debug: var=output.stdout_lines

    - name: set iptables
      shell: |
        iptables -F DOCKER-USER
        iptables -D DOCKER-USER -p tcp --match multiport --dport 8545,9130,9131,8067 -j DROP
        iptables -I DOCKER-USER -p tcp --match multiport --dport 8545,9130,9131,8067 -j DROP
        iptables -L DOCKER-USER

      register: output

    - debug: var=output.stdout_lines
