- name: Restart infura
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: download latest docker-blockbook repo && restart infura nodes
      shell: |
        rm -rf docker-blockbook-master
        wget -q https://github.com/SwingbyProtocol/docker-blockbook/archive/master.tar.gz
        tar -xf master.tar.gz         
        rm -f master.tar.gz

        docker system prune -f
        cd docker-blockbook-master/deployments/mainnet
        DIR=/var/swingby docker-compose down
        DIR=/var/swingby ./setup_bsc.sh
        DIR=/var/swingby ./init_bsc.sh
        DIR=/var/swingby docker-compose up -d --build bitcoind bsc
        sleep 40
        DIR=/var/swingby docker-compose up -d --build bb_btc bb_bsc

      register: output

    - debug: var=output.stdout_lines

    - name: set iptables
      shell: |
        iptables -F DOCKER-USER
        iptables -I DOCKER-USER -p tcp --match multiport --dport 8575,9130,9132,8067 -j DROP
        iptables -L DOCKER-USER

      register: output

    - debug: var=output.stdout_lines
