- name: Reset bsc
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: reset bsc
      shell: |
        cd docker-blockbook-master/deployments/mainnet
        DIR=/var/swingby docker-compose rm -sf bsc
        rm -rf /var/swingby/mainnet/bsc
        DIR=/var/swingby ./setup_bsc.sh
        DIR=/var/swingby ./init_bsc.sh
        DIR=/var/swingby docker-compose up -d bsc
      register: output

    - debug: var=output.stdout_lines
