- name: Setup infura
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: setup infura nodes
      shell: |
        cd docker-blockbook-master/deployments/mainnet
        DIR=/var/swingby docker-compose down

        killall b2-linux

        cd /var/swingby
        rm -f ./b2-linux
        wget -q https://github.com/Backblaze/B2_Command_Line_Tool/releases/latest/download/b2-linux
        chmod +x ./b2-linux
        ./b2-linux authorize-account 00082ac5807077d0000000004 K000r0mfkimneB/ZOgXCwMVNQtDzWHo

        mkdir -p /var/swingby/mainnet

        if ! pgrep -x "b2-linux" > /dev/null; then
          rm -rf /var/swingby/mainnet/*
          nohup ./b2-linux sync b2://var-swingby/mainnet/bsc /var/swingby/mainnet/bsc > /tmp/bsc.log 2> /tmp/bsc_err.log &
          nohup ./b2-linux sync b2://var-swingby/mainnet/bb_bsc /var/swingby/mainnet/bb_bsc > /tmp/bb_bsc.log 2> /tmp/bb_bsc_err.log &
          nohup ./b2-linux sync b2://var-swingby/mainnet/bitcoind /var/swingby/mainnet/bitcoind > /tmp/bitcoind.log 2> /tmp/bitcoind_err.log &
          nohup ./b2-linux sync b2://var-swingby/mainnet/bb_bitcoin /var/swingby/mainnet/bb_bitcoin > /tmp/bb_bitcoin.log 2> /tmp/bb_bitcoin_err.log &
        fi

      register: output

    - debug: var=output.stdout_lines
