- name: Setup bot
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: setup bot
      shell: |
        docker rm -f {{CONT_NAME}} 2> /dev/null || true
        docker pull swingbylabs/node-installer:{{TAG}}
        docker run -d \
          -v /var/swingby/node:/app/data \
          --name {{CONT_NAME}} \
          --log-opt max-size=10m --log-opt max-file=5 \
          -e BOT_TOKEN="{{BOT_TOKEN}}" \
          -e CHAT_ID="{{CHAT_ID}}" \
          -e IP_ADDR="{{IP_ADDR}}" \
          -e CONT_NAME="{{CONT_NAME}}" \
          -e HOST_USER="{{HOST_USER}}" \
          -e SSH_KEY="{{SSH_KEY}}" \
          -e REMOTE="{{REMOTE}}" \
          swingbylabs/node-installer:{{TAG}}

      register: output

    - debug: var=output.stdout_lines

    - name: check disk space
      shell: |
        df -mT /var/swingby | awk 'NR>1 { print $3 }'
      register: output
    - local_action:
        module: copy
        content: "{{ output.stdout }}"
        dest: "/tmp/var_size"

    - debug: var=output.stdout_lines

    - name: check mounth path space
      shell: |
        if [ -d "/var/swingby/mainnet" ]; then 
          sh -c "du -bs /var/swingby/mainnet 2> /dev/null" || true
        fi
      register: output
    - local_action:
        module: copy
        content: "{{ output.stdout }}"
        dest: "/tmp/dir_size"

    - debug: var=output.stdout_lines

    
