- name: Setup bot
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: download binary && install dependencies
      shell: |
        rm -rf docker-blockbook-master
        wget -q https://github.com/SwingbyProtocol/docker-blockbook/archive/master.tar.gz
        tar -xf master.tar.gz         
        rm master.tar.gz &&
        cd docker-blockbook-master
        chmod +x ./setup_docker.sh
        ./setup_docker.sh
      register: output

    - name: remove bot
      shell: |
        docker rm -f node-installer 2> /dev/null || true
      register: output

    - name: setup bot
      shell: |
        docker pull swingbylabs/node-installer
        docker image prune -f
        docker run -d --restart unless-stopped \
          -v /var/swingby/node:/app/data \
          --name node-installer \
          --log-opt max-size=10m --log-opt max-file=5 \
          -e BOT_TOKEN="{{BOT_TOKEN}}" \
          -e CHAT_ID="{{CHAT_ID}}" \
          -e IP_ADDR="{{IP_ADDR}}" \
          -e DOMAIN="{{DOMAIN}}" \
          -e HOST_USER="{{HOST_USER}}" \
          -e SSH_KEY="{{SSH_KEY}}" \
          -e REMOTE="{{REMOTE}}" \
          swingbylabs/node-installer
      register: output

    - debug: var=output.stdout_lines
