- name: Attach your domain to server
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: download nginx-certbot-master && install let's encrypt
      shell: |
        rm -rf nginx-certbot-master
        wget -q https://github.com/SwingbyProtocol/nginx-certbot/archive/master.tar.gz
        tar -xf master.tar.gz  
        rm master.tar.* 
        cd nginx-certbot-master
        DIR=/var/swingby/nginx_data DOMAIN={{DOMAIN}} FORWARD=172.17.0.1 PORT=8067 WITH_IDNEXERS={{WITH_IDNEXERS}} ./init-letsencrypt.sh
        if [ ! -e "/var/swingby/nginx_data/certbot/conf/live/{{DOMAIN}}/cert.pem" ]; then
          DIR=/var/swingby/nginx_data docker-compose down
          exit 0
        fi
        DIR=/var/swingby/nginx_data docker-compose down
        DIR=/var/swingby/nginx_data docker-compose up -d

      register: output

    - debug: var=output.stdout_lines
