- name: Restart infura
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: restart infura nodes
      shell: |
        cd docker-blockbook-master/deployments/mainnet
        DIR=/var/swingby docker-compose down
        DIR=/var/swingby docker-compose up -d --build

      register: output

    - debug: var=output.stdout_lines

    - name: set iptables
      shell: |
        iptables -D DOCKER-USER -p tcp --match multiport --dport 8545,9130,9131,8067 -j DROP
        iptables -I DOCKER-USER -p tcp --match multiport --dport 8545,9130,9131,8067 -j DROP
        iptables -L DOCKER-USER

      register: output

    - debug: var=output.stdout_lines
