- name: Deploy swingby node (btc_eth)
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  tasks:
    - name: remove swingby node
      shell: |
        docker rm -f swingby_node 2> /dev/null || true
      register: output

    - debug: var=output.stdout_lines

    - name: restart swingby node
      shell: |
        docker image prune -f
        docker pull swingbylabs/swapd-go:{{TAG}}
        docker run -d --restart unless-stopped \
          --name swingby_node \
          --net=bridge \
          -v /var/swingby/node/mainnet_btc_eth:/var/node_data \
          -p 12121:12121 \
          -p 8067:8067 \
          --log-opt max-size=10m --log-opt max-file=5 \
          swingbylabs/swapd-go:{{TAG}} \
          --home "/var/node_data" \
          --logger.level {{LOG_LEVEL}} \
          -k {{K_UNTIL}} \
          --p2p.connect {{BOOTSTRAP_NODE}}

      register: output

    - debug: var=output.stdout_lines
