- name: Check status
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: download node-agent & start agent
      shell: |
        rm -rf node-agent-master
        wget -q https://github.com/SwingbyProtocol/node-agent/archive/master.tar.gz
        tar -xf master.tar.gz         
        rm master.tar.gz
        cd node-agent-master
        killall node-agent
        nohup bin/linux_amd64/node-agent -c swingby_node -o /var/swingby/agent.json > node-agent.log &
        
      register: output

    - debug: var=output.stdout_lines

    - name: check infura nodes
      shell: |
        du -bs /var/swingby/mainnet
      register: output
    - local_action:
        module: copy
        content: "{{ output.stdout }}"
        dest: "/tmp/dir_size"

    - debug: var=output.stdout_lines

    - name: set iptables
      shell: |
        iptables -D DOCKER-USER -p tcp --match multiport --dport 8545,9130,9131,8067 -j DROP
        iptables -I DOCKER-USER -p tcp --match multiport --dport 8545,9130,9131,8067 -j DROP
        iptables -L DOCKER-USER

      register: output

    - debug: var=output.stdout_lines

