- name: Setup node
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: download docker-blockbook && install dependencies
      shell: |
        apt update
        apt install wget -y
        rm -rf docker-blockbook-master
        wget -q https://github.com/SwingbyProtocol/docker-blockbook/archive/master.tar.gz
        tar -xf master.tar.gz         
        rm master.tar.gz &&
        cd docker-blockbook-master
        chmod +x ./setup_docker.sh
        ./setup_docker.sh
      register: output

    - debug: var=output.stdout_lines
  
  