- name: Deploy swingby node (tbtc_goerli)
  hosts: server
  user: "{{HOST_USER}}"
  become: yes
  tasks:
    - name: restart swingby node
      shell: >
        docker image prune -f && 
        docker pull swingbylabs/swapd-go:{{TAG}} &&
        docker run -d \
          -v /var/swingby/node/testnet_tbtc_bc:/var/node_data \
          -p 12121 \
          -p 8067 \
          --log-opt max-size=10m --log-opt max-file=5 \
          swingbylabs/swapd-go:{{TAG}} \
          --home "/var/node_data" \
          --p2p.listen {{IP_ADDR}} \
          --p2p.port 12121  \
          --rest.listen 0.0.0.0 \
          -k {{K_UNTIL}}
      register: output
      environment:
        TAG: "{{TAG}}"
        IP_ADDR: "{{IP_ADDR}}"
        BOOTSTRAP_NODE: "{{BOOTSTRAP_NODE}}"
        K_UNTIL: "{{K_UNTIL}}"
