- name: Setup infura
  hosts: server
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: setup infura services
      shell: >
        apt-get update && apt-get install -y docker.io && service docker start

      register: output
