- name: Setup infura
  hosts: server
  user: root
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install docker & docker-compose
      shell: >
        apt update && 
        apt install -y docker.io git && 
        service docker start &&
        sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose &&
        chmod +x /usr/local/bin/docker-compose

      register: output
    - name: setup nodes
      shell: >
        wget -q https://github.com/SwingbyProtocol/docker-blockbook/archive/master.tar.gz &&
        tar -xf master.tar.gz &&         
        rm master.tar.gz &&
        cd docker-blockbook-master/deployments/testnet && 
        docker-compose down &&
        dir="/var/swingby" docker-compose up -d
      register: output
